# Essential Libraries & Tools #
Scikit-learn is one of the most prominent Machine Learning toos used in python.

NumPy hosts lots of linear algebra functions necessary for ML

In [ ]:
pip install Numpy

SyntaxError: invalid syntax (1791898764.py, line 2)

In [5]:
pip install scikit-learn

  Using cached scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp311-cp311-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/41.2 MB ? eta -:--:--
   - -------------------------------------- 1.0/41.2 MB 6.3 MB/s eta 0:00:07
   --- ------------------------------------ 3.1/41.2 MB 8.0 MB/s eta 0:00:05
   ----- ---------------------------------- 5.5/41.2 MB 9.3 MB/s eta 0:00:04
   -------- ------------------------------- 8.9/41.2 MB 10.9 MB/s eta 0:00:03
   ----------- ---------------------------- 12.1/41.2 MB 11.8 MB/s eta 0:00:03
   -------------- ------------------------- 15.2/41.2 MB 12.4 MB/s eta 0:00:03
   ------------------ --------------------- 18.6/41.2 MB 12.9 MB/s eta 0:00:02
   --------------------- ------------------ 21.8/41.2 MB 13.2 MB/s eta 0:00:02
   ------------------------ --------------- 24.9/41.2 MB 13.5 MB/s eta 0:00:02
   ---------

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
